"""Add saved_file_path to documents table

Revision ID: 8afe319246de
Revises: 111ca9ad58e0
Create Date: 2025-11-18 14:30:14.240760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afe319246de'
down_revision: Union[str, Sequence[str], None] = '111ca9ad58e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('saved_file_path', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'saved_file_path')
    # ### end Alembic commands ###
